### ISSUE TITLE
Unsafe yaml loading

### ISSUE THREAD

**Issue by JoeyJoJoJrShabadu** [mjdorma/funconf#3]
Funconf uses yaml.load which allows for loading of unsafe yaml including the python/object/apply construct which will arbitrarily load a module and execute a function.

As an example we can do the following with the demo code:

demo.conf

``` yaml
#
# Foo
#
foo:
  bar: 4
  moo:
  - how
  - are
  - you
  buzz: !!python/object/apply:buzz.sus [bar, moo]

#
# Bread
#
bread:
  butter: win
  milk: fail
```

``` python
def sus(bar, moo):
    print "This is awfully suspicious.... %s - %s" % (bar, moo)
    exit()
```

Might be worth using the safe_load function instead.  We are more likely to raise a yaml.constructor.ConstructorError, not sure if this is desirable and whether we should raise it as a more specific error to unsafe behaviour if found...
